### PR TITLE
8/26: Fix bug by closing Natural Language API Client

### LINKED ISSUE #187: Permanent fix for non-closing NLClient

### PR DESCRIPTION
**Pull request by annemariecabs**
Add closure for Natural Language API client, which just closes the internal LanguageServiceClient of the class. Integrates this closure in to the prompt creation suite. Fix #187.

### CODE REVIEW

File: backstory/src/main/java/com/google/sps/story/data/NLServiceClient.java [hunk 1]
```diff
@@ -162,6 +162,14 @@ public NLServiceClient(LanguageServiceClient client) throws IllegalArgumentExcep
     return map;
   }
 
+  /**
+   * Close out the NLServiceClient by clsoing out
```
Comment (ykjchen) [inline backstory/src/main/java/com/google/sps/story/data/NLServiceClient.java:166]: typo/clsoing

File: backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java [hunk 2]
```diff
@@ -25,33 +25,29 @@
...
    * @param words A list of Strings containing keywords for prompts.
    * @return A mapping of WordTypes to given words.
+   * @throws IOException Exception for network problem.
    */
-  public Map<WordType, List<String>> groupByWordType(List<String> words) {
+  public Map<WordType, List<String>> groupByWordType(List<String> words) throws IOException {
+    NLServiceClient wordClassifier = new NLServiceClient();
+
+    Map<WordType, List<String>> groupings = wordClassifier.groupByWordType(words);
+    wordClassifier.close();
```
Comment (ykjchen) [inline backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java:49]: What does it mean to close the client? It looks like the client is used again after closing it, which is somewhat unintuitive.

File: backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java [hunk 3]
```diff
@@ -25,33 +25,29 @@
...
   /**
    * Classifies an input of strings based on their part of speech.
    *
    * @param words A list of Strings containing keywords for prompts.
    * @return A mapping of WordTypes to given words.
+   * @throws IOException Exception for network problem.
    */
-  public Map<WordType, List<String>> groupByWordType(List<String> words) {
+  public Map<WordType, List<String>> groupByWordType(List<String> words) throws IOException {
+    NLServiceClient wordClassifier = new NLServiceClient();
```
Comment (ykjchen) [inline backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java:46]: Can this be named nlServiceClient so that the type of the variable is clearer?

File: backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java (hunk 2 above)
Comment (annemariecabs) [reply backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java:49]: You're totally right. The intent is actually that the client is not used again. That was a typo by me. I changed it. Closing the client really means closing the connection with the API (the LanguageServiceClient created in the constructor).

File: backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java (hunk 3 above)
Comment (annemariecabs) [reply backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java:46]: I changed this. Thanks!

File: backstory/src/main/java/com/google/sps/story/data/NLServiceClient.java (hunk 1 above)
Comment (annemariecabs) [reply backstory/src/main/java/com/google/sps/story/data/NLServiceClient.java:166]: Will fix.

File: backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java (hunk 3 above)
Comment (annemariecabs) [reply backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java]: Done

File: backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java (hunk 2 above)
Comment (annemariecabs) [reply backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java]: Done

File: backstory/src/main/java/com/google/sps/story/data/NLServiceClient.java (hunk 1 above)
Comment (annemariecabs) [reply backstory/src/main/java/com/google/sps/story/data/NLServiceClient.java]: Done

**Comment by ykjchen** [comment]
re: the PR description, what's the bug that this fixes?

**Comment by annemariecabs** [comment]
> @annemariecabs re: the PR description, what's the bug that this fixes?

@ykjchen When the app is deployed, if the LanguageServiceClient isn't closed, then it causes a RuntimeException because managed channels need to be closed.

File: backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java [hunk 4]
```diff
@@ -25,34 +25,30 @@
...
   /** Client object for word fetching */
   private DatamuseRequestClient wordFetcher;
 
   /**
-   * Initialize API objects.
-   *
-   * @throws IOException Exception for network problem.
+   * Initialize Datamuse API object.
    */
   public PromptManagerAPIsClient() throws IOException {
```
Comment (UdayKalra) [inline backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java:34]: If the throws tag is still present, throws should still be in the javadoc?

Comment (annemariecabs) [reply backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java]: The throws tag should not still be present. I'll remove it. Thanks!

Comment (annemariecabs) [reply backstory/src/main/java/com/google/sps/story/PromptManagerAPIsClient.java]: Done
